services:
  # A Docker web service
  - type: web
    name: fhir-ig-explorer
    rootDir: dqm
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn dqm.api:app --host 0.0.0.0 --port $PORT
